# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ARG CUDA_VERSION=12.9.1
FROM nvcr.io/nvidia/cuda:${CUDA_VERSION}-cudnn-devel-ubuntu24.04 AS base

# Set timezone and install all packages
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        tzdata \
        software-properties-common netcat-openbsd kmod unzip openssh-server \
        curl wget lsof zsh ccache htop git-lfs tree \
        python3 python3-pip python3-dev libpython3-dev python3-venv \
        build-essential cmake \
        libopenmpi-dev libnuma1 libnuma-dev \
        libibverbs-dev libibverbs1 libibumad3 \
        librdmacm1 libnl-3-200 libnl-route-3-200 libnl-route-3-dev libnl-3-dev \
        ibverbs-providers infiniband-diags perftest \
        libgoogle-glog-dev libgtest-dev libjsoncpp-dev libunwind-dev \
        libboost-all-dev libssl-dev \
        libgrpc-dev libgrpc++-dev libprotobuf-dev protobuf-compiler-grpc \
        pybind11-dev \
        libhiredis-dev libcurl4-openssl-dev \
        libczmq4 libczmq-dev \
        libfabric-dev \
        patchelf \
        nvidia-dkms-550 \
        devscripts debhelper fakeroot dkms check libsubunit0 libsubunit-dev \
 && ln -sf /usr/bin/python3 /usr/bin/python \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get clean

# Install SGLang missing package for blackwell build type
RUN python3 -m pip install --break-system-packages openai httpx

# GDRCopy installation
RUN mkdir -p /deps/gdrcopy && cd /deps \
 && git clone https://github.com/NVIDIA/gdrcopy.git -b v2.4.4 \
 && cd gdrcopy/packages \
 && CUDA=/usr/local/cuda ./build-deb-packages.sh \
 && dpkg -i gdrdrv-dkms_*.deb libgdrapi_*.deb gdrcopy-tests_*.deb gdrcopy_*.deb \
 && cd 

# Fix DeepEP IBGDA symlink
RUN ln -sf /usr/lib/$(uname -m)-linux-gnu/libmlx5.so.1 /usr/lib/$(uname -m)-linux-gnu/libmlx5.so

FROM base AS build-image

ARG SGLANG_COMMIT=ff1f68252c2b5b343aa6ef2aa14e6d4753ae4871
ARG BUILD_TYPE=blackwell
ARG DEEPEP_COMMIT=1b14ad661c7640137fcfe93cccb2694ede1220b0
ARG CMAKE_BUILD_PARALLEL_LEVEL=2
ARG SGL_KERNEL_VERSION=0.3.4
ENV DEBIAN_FRONTEND=noninteractive \
    CUDA_HOME=/usr/local/cuda \
    GDRCOPY_HOME=/usr/src/gdrdrv-2.4.4/ \
    NVSHMEM_DIR=/sgl-workspace/nvshmem/install \
    BUILD_TYPE=${BUILD_TYPE} \
    TORCH_CUDA_ARCH_LIST="10.0 12.0"

# Clone and install SGLang
WORKDIR /sgl-workspace
RUN python3 -m pip install --break-system-packages --no-cache-dir --upgrade setuptools html5lib six \
    && git clone --depth 1 https://github.com/sgl-project/sglang.git \
    && cd sglang \
    && git fetch --depth=1 origin ${SGLANG_COMMIT} \
    && git checkout ${SGLANG_COMMIT} \
    && case "$CUDA_VERSION" in \
        12.9.1) CUINDEX=129 ;; \
        *) echo "Unsupported CUDA version: $CUDA_VERSION" && exit 1 ;; \
    esac \
    && if [ "$CUDA_VERSION" = "12.9.1" ]; then \
        python3 -m pip install --break-system-packages --no-cache-dir nvidia-nccl-cu12==2.27.6 --force-reinstall --no-deps ; \
        python3 -m pip install --break-system-packages --no-cache-dir https://github.com/sgl-project/whl/releases/download/v${SGL_KERNEL_VERSION}/sgl_kernel-${SGL_KERNEL_VERSION}+cu129-cp310-abi3-manylinux2014_$(uname -m).whl --force-reinstall --no-deps ; \
    fi \
    && python3 -m pip install --break-system-packages --no-cache-dir -e "python[${BUILD_TYPE}]" --extra-index-url https://download.pytorch.org/whl/cu${CUINDEX} \
    && python3 -m flashinfer --download-cubin

# Download source files
RUN wget https://developer.download.nvidia.com/compute/redist/nvshmem/3.3.9/source/nvshmem_src_cuda12-all-all-3.3.9.tar.gz && \
    git clone https://github.com/fzyzcjy/DeepEP.git && \
    cd DeepEP && git checkout ${DEEPEP_COMMIT} && cd .. && \
    tar -xf nvshmem_src_cuda12-all-all-3.3.9.tar.gz && \
    mv nvshmem_src nvshmem && \
    rm -f /sgl-workspace/nvshmem_src_cuda12-all-all-3.3.9.tar.gz

# Build and install NVSHMEM
RUN cd /sgl-workspace/nvshmem && \
    NVSHMEM_SHMEM_SUPPORT=0 \
    NVSHMEM_UCX_SUPPORT=0 \
    NVSHMEM_USE_NCCL=0 \
    NVSHMEM_MPI_SUPPORT=0 \
    NVSHMEM_IBGDA_SUPPORT=1 \
    NVSHMEM_PMIX_SUPPORT=0 \
    NVSHMEM_TIMEOUT_DEVICE_POLLING=0 \
    NVSHMEM_USE_GDRCOPY=1 \
    cmake -S . -B build/ -DCMAKE_INSTALL_PREFIX=${NVSHMEM_DIR} -DCMAKE_CUDA_ARCHITECTURES="90;100;120" && \
    cmake --build build --target install -j${CMAKE_BUILD_PARALLEL_LEVEL}

# Install DeepEP
RUN cd /sgl-workspace/DeepEP && \
    NVSHMEM_DIR=${NVSHMEM_DIR} pip install --break-system-packages .

# Python tools
RUN python3 -m pip install --no-cache-dir --break-system-packages \
        datamodel_code_generator \
        mooncake-transfer-engine==0.3.5 \
        scikit-build-core

# Install development tools and utilities
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/arm64/cuda-keyring_1.1-1_all.deb \
    && dpkg -i cuda-keyring_1.1-1_all.deb \
    && rm cuda-keyring_1.1-1_all.deb \
    && apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        nsight-systems-cli\
        locales \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Set up locale
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Set workspace directory
WORKDIR /sgl-workspace/sglang

##################################
##### Wheel Build Image ##########
##################################

FROM quay.io/pypa/manylinux_2_28_aarch64 AS wheel_builder

RUN dnf update -y \
    && dnf install -y llvm-toolset protobuf-compiler python3.12-devel wget \
    && dnf clean all \
    && rm -rf /var/cache/dnf

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
# Create virtual environment
RUN mkdir -p /opt/dynamo/venv && \
    uv venv /opt/dynamo/venv --python 3.12

# Activate virtual environment
ENV VIRTUAL_ENV=/opt/dynamo/venv \
    RUSTUP_HOME=/usr/local/rustup \
    RUST_VERSION=1.89.0 \
    CARGO_HOME=/usr/local/cargo \
    CARGO_TARGET_DIR=/opt/dynamo/target \
    PATH="/usr/local/cargo/bin:/opt/dynamo/venv/bin:${PATH}"

RUN wget --tries=3 --waitretry=5 \
    "https://static.rust-lang.org/rustup/archive/1.28.1/aarch64-unknown-linux-gnu/rustup-init" \
    && chmod +x rustup-init \
    &&./rustup-init -y \
        --no-modify-path \
        --profile minimal \
        --default-toolchain $RUST_VERSION \
        --default-host $(uname -m)-unknown-linux-gnu \
    && rm rustup-init \
    && chmod -R a+w $RUSTUP_HOME $CARGO_HOME

RUN --mount=type=bind,source=./container/deps/requirements.txt,target=/tmp/requirements.txt \
    uv pip install --requirement /tmp/requirements.txt

WORKDIR /opt/dynamo

# Copy configuration files first for better layer caching
COPY pyproject.toml README.md LICENSE Cargo.toml Cargo.lock rust-toolchain.toml hatch_build.py /opt/dynamo/

# Copy source code
COPY lib/ /opt/dynamo/lib/
COPY components/ /opt/dynamo/components/

ARG CARGO_BUILD_JOBS
# Set CARGO_BUILD_JOBS to 16 if not provided
# This is to prevent cargo from building $(nproc) jobs in parallel,
# which might exceed the number of opened files limit.
ENV CARGO_BUILD_JOBS=${CARGO_BUILD_JOBS:-16}

# # Build dynamo wheel
RUN uv build --wheel --out-dir /opt/dynamo/dist  && \
    cd /opt/dynamo/lib/bindings/python && \
    uv pip install maturin[patchelf] && \
    maturin build --release --out /opt/dynamo/dist 

FROM build-image AS sglang-wideep

ARG MODE="hopper"
ARG ARCH="amd64"
ARG ARCH_ALT="x86_64"
ARG NIXL_UCX_REF="v1.19.0"
ARG NIXL_TAG="0.5.0"
ARG CMAKE_VERSION="3.31.8"
ARG RUST_VERSION="1.89.0"
ARG CARGO_BUILD_JOBS="16"

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends\
      ninja-build pybind11-dev patchelf net-tools \
      build-essential protobuf-compiler libssl-dev pkg-config \
      clang libclang-dev git rapidjson-dev zlib1g-dev && \
    pip install --break-system-packages meson meson-python wheel build

RUN wget --tries=3 --waitretry=5 \
      https://github.com/nats-io/nats-server/releases/download/v2.10.28/\
nats-server-v2.10.28-arm64.deb && \
    dpkg -i nats-server-v2.10.28-arm64.deb && rm nats-server-v2.10.28-arm64.deb

ENV ETCD_VERSION="v3.5.21"
RUN wget --tries=3 --waitretry=5 \
      https://github.com/etcd-io/etcd/releases/download/${ETCD_VERSION}/\
etcd-${ETCD_VERSION}-linux-arm64.tar.gz -O /tmp/etcd.tar.gz && \
    mkdir -p /usr/local/bin/etcd && \
    tar -xzf /tmp/etcd.tar.gz \
        -C /usr/local/bin/etcd --strip-components=1 && \
    rm /tmp/etcd.tar.gz

ENV PATH=/usr/local/bin/etcd:$PATH

# Build UCX + NIXL for x86/hopper until its fully tested on GB200
RUN if [ "$MODE" = "hopper" ]; then \
      DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends\
        libibverbs-dev rdma-core ibverbs-utils libibumad-dev \
        libnuma-dev librdmacm-dev ibverbs-providers autoconf libtool && \
      # UCX from source
      rm -rf /opt/hpcx/ucx /usr/local/ucx && \
      cd /usr/local/src && \
      git clone https://github.com/openucx/ucx.git && \
      cd ucx && git checkout $NIXL_UCX_REF && \
      ./autogen.sh && \
      ./configure \
        --prefix=/usr/local/ucx \
        --enable-shared \
        --disable-static \
        --disable-doxygen-doc \
        --enable-optimizations \
        --enable-cma \
        --enable-devel-headers \
        --with-cuda=/usr/local/cuda \
        --with-verbs \
        --with-efa \
        --with-dm \
        --with-gdrcopy=/usr/local \
        --enable-mt && \
      make -j && make install-strip && ldconfig && \
      # NIXL
      git clone https://github.com/ai-dynamo/nixl.git /opt/nixl && \
      cd /opt/nixl && git checkout $NIXL_TAG && \
      pip install --break-system-packages . \
        --config-settings="setup-args=-Ducx_path=/usr/local/ucx"; \
    fi

ENV LD_LIBRARY_PATH=/usr/lib:/usr/local/ucx/lib:$LD_LIBRARY_PATH

# Unneeded in this particular image, but leaving here for reference
# RUN pip install --break-system-packages sglang-router==0.1.9

# Dynamo
WORKDIR /sgl-workspace

ENV CARGO_TARGET_DIR=/opt/dynamo/target 

COPY --from=wheel_builder /opt/dynamo/dist/*.whl /opt/dynamo/wheelhouse/
COPY --from=wheel_builder $CARGO_TARGET_DIR $CARGO_TARGET_DIR

RUN python3 -m pip install --no-cache-dir --break-system-packages \
        /opt/dynamo/wheelhouse/ai_dynamo_runtime*cp312*.whl \
        /opt/dynamo/wheelhouse/ai_dynamo*any.whl

COPY /components/backends/sglang ./dynamo/components/backends/sglang

# Enable forceful shutdown of inflight requests
ENV SGL_FORCE_SHUTDOWN=1

WORKDIR /sgl-workspace/dynamo/components/backends/sglang
