# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[project]
name = "data-generator"
version = "0.1.0"
description = "Data generator library for LLM benchmarks"
readme = "README.md"
authors = [
    {name = "NVIDIA CORPORATION & AFFILIATES"}
]
license = {text = "Apache-2.0"}
requires-python = ">=3.10"

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Operating System :: POSIX :: Linux",
]

dependencies = [
    "aiconfigurator==0.2.0",
    "networkx",
    "pandas",
    "pydantic>=2",
    "tabulate",
    "types-tabulate",
    "transformers",
    "pytest-mypy",
]

[project.scripts]
datagen = "prefix_data_generator.cli:main"

[project.urls]
Repository = "https://github.com/ai-dynamo/dynamo.git"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv]
override-dependencies = [
    "gradio==5.47.1"
]

[tool.setuptools]
packages = ["prefix_data_generator"]

[tool.setuptools.package-data]
prefix_data_generator = ["**/*.py"]

[tool.mypy]
explicit_package_bases = true
ignore_missing_imports = true
check_untyped_defs = true

[tool.pytest.ini_options]
addopts = [
    "-ra",
    "--showlocals",
    "--strict-markers",
    "--strict-config",
    "--mypy",  # This flag enables mypy type checking during pytest runs
    "--ignore-glob=*model.py",
    "--ignore-glob=*_inc.py",
    "--ignore-glob=deploy/cloud/api-store/*",
]